# Model Configuration
models:
  yolo: 'models/yolov8n.pt'
  reid_gpu: 'osnet_ain_x1_0'
  reid_cpu: 'osnet_ain_x1_0'
  reid_num_classes: 1501

# ReID Parameters
reid:
  alpha: 0.3
  threshold: 0.25
  temporal_frames: 3
  max_gallery_size: 100
  height: 256
  width: 128
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  device: "cpu"
  min_features_confirmed: 15

# Tracker Parameters
tracker:
  max_age: 30
  n_init: 2
  max_cosine_distance: 0.3
  nn_budget: 30
  model: "models/mars-small128.pb"

# Detection Parameters
detection:
  confidence_threshold: 0.5
  person_class_id: 0
  device: "cpu"
  min_box_ratio: 1.5
  max_box_ratio: 3.5

  min_height_box: [0, 0]
  max_height_box: [1000, 1000]
  #min_height_box: [180, 100]
  #max_height_box: [300, 200]
# Paths
paths:
  embeddings_dir: 'embeddings'

# Video Processing
video:
  max_videos: 2
  sources: ["videos_exemples/MOT17-1.webm"]
  #sources: [0]
  #sources: [0,1]