# Model Configuration
models:
  # Fichier modèle
  yolo: 'models/yolov8n.pt'

  # Modèle pour la ReID (Reconnaissance des personnes)
  # Choisir le modèle voulu :
  # osnet_ain_x1_0 : Modele le plus robuste pour faire de la reconnaissance de personnes.
  # osnet_x1_0 : Modele de base
  # resnet50 : Modele générale pour la reconnaissance des personnes.
  reid: 'osnet_ain_x1_0'
  # Fichier pour le modèle (Prendre un fichier correspondant au modele de ReID.
  reid_model_file: 'models/osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth'

# ReID Parameters
reid:
  threshold: 0.25 # Seuil de distance pour la ReID
  max_gallery_size: 100
  device: "cpu"
  min_features_confirmed: 15

# Tracker Parameters
tracker:
  max_cosine_distance: 0.3
  nn_budget: 30
  model: "models/mars-small128.pb" # Modèle permettant le tracking avec DeepSORT.

# Detection Parameters
detection:
  confidence_threshold: 0.5
  person_class_id: 0
  device: "cpu"
  min_box_ratio: 1.5 # Ratio (hauteur / largeur) Minimum
  max_box_ratio: 3.5 # Ratio (hauteur / largeur) Maximum

  min_height_box: [0, 0]
  max_height_box: [1000, 1000] # à regler (une valeur pour chaque caméra (camera 1 nombre 1, caméra 2 nombre 2).
  #min_height_box: [180, 100]
  #max_height_box: [300, 200]

# Paths
paths:
  embeddings_dir: 'embeddings'

# Video Processing
video:
  max_videos: 2
  sources: ["videos_exemples/MOT17-1.webm", "videos_exemples/MOT17-1.webm"]
  #sources: [0]
  #sources: [0,1]